export enum BrowserActions {
  OPEN_PAGE = 'OPEN_PAGE',
  CLOSE_PAGE = 'CLOSE_PAGE',
  SET_VALUE = 'SET_VALUE',
  CLICK_ELEMENT = 'CLICK_ELEMENT',
  ENABLE_ELEMENT = 'ENABLE_ELEMENT',
  DISABLE_ELEMENT = 'DISABLE_ELEMENT',
  IS_DISABLED = 'IS_DISABLED',
}
